### ISSUE TITLE
[Use Case]: Repatriation

### ISSUE THREAD

**Issue by edsu** [webrecorder/specs#116]
### Describe a use case for WACZ format.

As a human rights activist I want to be able to archive a website that is at risk due to political instability, censorship, or war so that the data that can be returned or repatriated to the original publishers and community. While it would be useful to put the content back on the web, it might also be useful to be able to give copies to community members that they could look at locally on their own computers, and for the websites to be easily transferable across the network or on physical media (thumbdrives, etc).

### Additional Requirements

- [X] List of entry pages to start browsing from
- [ ] Full-text search index
- [ ] Technical metadata about the web archive
- [X] User-defined descriptive metadata
- [ ] Screenshots of key pages
- [ ] Encryption of data
- [ ] Proof of Authenticity (Signing and Verification)
- [ ] Fast access to multiple WACZ files in aggregate
- [ ] Crawl or capture logs

### How will web archives be created for this use case?

- [X] Manually, using a browser to capture exact content as directed by the user.
- [X] Automatically, using a crawler to crawl desired content, either once or on a specified schedule.

### Sensitive private content and access

- [X] No, this use case focuses on archiving publicly accessible data only, and web archive can be made public.
- [X] No, this use case focuses on archiving publicly data only, but web archive is not inteded to be public.
- [X] Yes, this use case involves archiving data that is not public, and the web archive should not be made public.

**Comment by pbinkley** [comment]
This is great. I suggest striking "after the conflict is over", since the second sentence covers cases that could apply during the conflict (by making copies available to communities in exile for example).
