### ISSUE TITLE
wacz-auth: `signedData` or `signatureData` in `datapackage-digest.json`?

### ISSUE THREAD

**Issue by matteocargnelutti** [webrecorder/specs#131]
There seems to be a discrepancy between https://specs.webrecorder.net/wacz-auth/0.1.0/#data-package-digest-file and https://github.com/webrecorder/specs/blob/main/wacz-auth/spec.md#wacz-signature-file-and-format 

The official spec document indicates that the output of the signing operation should be stored under `signatureData`, but the latest version (?) of the spec uses `signedData` instead.

Given that `py-wacz`, `authsign` and `wabac.js` all use `signedData`, my assumption is that the published spec doc is out of date?

Cheers,

**Comment by edsu** [comment]
Thank you for noticing the `signedData` issue and taking the time to clean up the other issues -- much appreciated @matteocargnelutti!

**Comment by edsu** [comment]
This was fixed in #132 -- thanks for the fixes @matteocargnelutti!
