### ISSUE TITLE
New Spec: IPFS Chunking of WACZ/WARC

### ISSUE THREAD

**Issue by RangerMauve** [webrecorder/specs#134]
Related to how we're uploading archives to IPFS in archiveweb.page and soon browsertrix-cloud.

We should go over the following:

- Briefly describe how IPFS UnixFS works
- How UnixFS files can be made up of chunks
- Our [ipfs-composite-files](https://github.com/webrecorder/ipfs-composite-files) repo
- How we use it with [zip file chunking](https://github.com/webrecorder/ipfs-composite-files#in-place-zip)
- How this relates to WACZ
- Benefits of this approach and future plans

**Comment by edsu** [comment]
@RangerMauve if you are still looking for where to add the text maybe you could add a directory `ipfs-chunking` and then create a version directory in there e.g. `0.0.1` and put your HTML file in there.

If you would prefer to author in Markdown and want me to get it into the respec HTML shell just put your Markdown doc in that directory and I can help. It's not the most pleasant thing in the world dropping the Markdown into the HTML frame, but it's not so bad once you've done it a few times.

**Comment by ikreymer** [comment]
Done, initial spec draft merged over and respec autogenerated!
