### ISSUE TITLE
Can you make a converter tool for converting html files to fully warc files so that it can work properly with rhizome conifer please.

### ISSUE THREAD

**Issue by KaineRecycler** [webrecorder/specs#137]
Dear webrecorder help support team my name is Kaine Dube and I am a user on the conifer website and I want to submit a new inquiry for allowing users like me can convert static and html files to fully functional warc files so that it will be easier for users upload there warc files to conifer after when you convert them to fully created warc files so It's kinda like similar to python warcit converter that is designed for windows compatible computers but this one that I was talking about is a bit like the same thing but compatible with all devices so this feature will include a drag and drop file uploader a convert button at the bottom and a empty box at the bottom where the fully finished warc file is converted to a warc file once after the conversion is completed before you upload it to conifer easily without downloading python warcit on any other device that is not  compatible with the warcit converter tool for windows computer or Linux computer system.

But yes that concludes my inquiry about this new tool for webrecorder and for conifer and so it can be added to your webrecorder tools platform that you have already made earlier for best web archiving tools for 2023.

**Comment by ikreymer** [comment]
We are not currently planning to add other tools besides warcit for this. This is also not the right place for this discussion.
