### ISSUE TITLE
[Use Case]: timestamping WARCs inside a WACZ

### ISSUE THREAD

**Issue by mikevandijk** [webrecorder/specs#140]
### Describe a use case for WACZ format.

As a an owner of a capture I want to be sure that the capture files inside a WACZ file are of the date they claim to be so that I can prove the time of capture in court.

Current WACZ spec seems to only provide options to timestamp the complete WACZ which in theory could mean that the files inside the WACZ could have been modified between time of capture and time they the WACZ got timestamped.

Adding the option to also timestamp the WARC files/captures themselves would solve this.

### Additional Requirements

- [ ] List of entry pages to start browsing from
- [ ] Full-text search index
- [ ] Technical metadata about the web archive
- [ ] User-defined descriptive metadata
- [ ] Screenshots of key pages
- [ ] Encryption of data
- [X] Proof of Authenticity (Signing and Verification)
- [ ] Fast access to multiple WACZ files in aggregate
- [ ] Crawl or capture logs

### How will web archives be created for this use case?

- [ ] Manually, using a browser to capture exact content as directed by the user.
- [X] Automatically, using a crawler to crawl desired content, either once or on a specified schedule.

### Sensitive private content and access

- [X] No, this use case focuses on archiving publicly accessible data only, and web archive can be made public.
- [ ] No, this use case focuses on archiving publicly data only, but web archive is not inteded to be public.
- [ ] Yes, this use case involves archiving data that is not public, and the web archive should not be made public.

**Comment by ikreymer** [comment]
@mikevandijk I'm not sure I understand what you mean. Each WARC record is already timestamped, by definition, as the timestamp is part of the WARC spec, which represents the time the page is captured.

The spec also includes the hash of each WARC file in the datapackage.json, and the signature of the datapackage.json in the datapackage-digest.json. If any file in the WACZ zip is modified after it is signed, the hash validation of the constituent WARC files (or any other file) will be detected, and it will be considered invalid by validation tools.

Are you asking about having a potentially separate timestamp for WARC files outside of the data that they contain, eg. if the WARC was created with older data stored in a different format? I'm not sure if that's needed, as there is a way to reflect this in the WARC itself, for example, if say you have a capture from 2020 but the WARC was created in 2023, there is the `WARC-Creation-Date` header which can be used for this in each WARC record to indicate when it was created.
This allows for more flexible option to separate the date of the content from the *creation date* of the WARC record itself.

**Comment by mikevandijk** [comment]
thanks for the quick reply. We will re-evaluate based on your feedback. Closing this for now.
