### ISSUE TITLE
[Use Case]: Resources for investigative journalism

### ISSUE THREAD

**Issue by edsu** [webrecorder/specs#78]
### Describe a use case for WACZ format.

A journalist uses the browser to create archives of primary source material, documenting sources which may be sensitive and may be deleted in the future, including social media posts. They ensure the data is archived and store the WACZ file in encrypted storage. 

### Additional Requirements

- [ ] List of entry pages to start browsing from
- [ ] Full-text search index
- [X] Technical metadata about the web archive
- [X] User-defined descriptive metadata
- [ ] Screenshots of key pages
- [X] Encryption of data
- [X] Proof of Authenticity (Signing and Verification)
- [ ] Fast access to multiple WACZ files in aggregate
- [ ] Crawl or capture logs

### How will web archives be created for this use case?

- [ ] Manually, using a browser to capture exact content as directed by the user.
- [ ] Automatically, using a crawler to crawl desired content, either once or on a specified schedule.

### Sensitive private content and access

- [ ] No, this use case focuses on archiving publicly accessible data only, and web archive can be made public.
- [ ] No, this use case focuses on archiving publicly data only, but web archive is not inteded to be public.
- [X] Yes, this use case involves archiving data that is not public, and the web archive should not be made public.

**Comment by atomotic** [comment]
journalists may want to protect their identity using some kinds of vpn or TOR, hiding their origin IP address.
currently archiveweb.page extension can be used with brave+tor [1][2]

does the WACZ metadata should keep this information, as proof of authenticity?


[1] https://docuverse.notion.site/archiveweb-page-brave-tor-939aacd4100c44edb0f7ec5fa4ecc446
[2] https://forum.webrecorder.net/t/archiveweb-page-in-brave-tor/97

**Comment by ikreymer** [comment]
That's an interesting question, not sure we have a clear answer yet. I guess it could be included in the technical metadata in some way.. Actually, I'm not sure the extension is aware that its being used through Tor necessarily?

I wonder about the implications of saving the IP of exit nodes as well..

The proof-of-authenticity so far has been approached from the client side so, it may not matter exactly, eg. we would claim the data was seen by the client, regardless of which IP it was loaded from. I think we'd have to think about the authentication approaches to browser-based web archiving, which we haven't yet enumerated. For example, currently archiveweb.page actually creates a key pair and signs the WACZ with that key pair, though the public key is not published anywhere.

**Comment by atomotic** [comment]
yeah, i think is not useful to save infomation about the exit nodes, maybe is just enough some kind of field in the metadata that claims that TOR (or a generic anonymized network) has been used.
not sure if the extension itself can obtain information about the TOR circuit (neither [is available in Brave UI](https://github.com/brave/brave-browser/issues/15163))

**Comment by edsu** [comment]
I've updated this [use case in the doc](https://specs.webrecorder.net/use-cases/0.1.0/#resources-for-investigative-journalism) to reflect the Tor use.

This did prompt me to add a tangentially related [threat](https://specs.webrecorder.net/use-cases/0.1.0/#journalist-gets-hacked) about the potential for private information to leak out into the archive:
