### ISSUE TITLE
[Use Case]: author caches open web references at time of citation, to deposit or submit later along with manuscript

### ISSUE THREAD

**Issue by nullhandle** [webrecorder/specs#89]
### Describe a use case for WACZ format.

An author of a scholarly work archives cited open web resources so that these can later be deposited in a repository or submitted to a publisher along with the manuscript. That the author carries out the archiving as close in time as possible to the inclusion of the citation, as well as has the opportunity to themself review the fidelity of the archival snapshot to what they intended, minimizes the potential for material content drift. The risk of content drift is greater if archiving of citations relies either on best-effort archiving (e.g., Internet Archive web-wide crawl) or it only happens on being deposited into a repository (e.g., via a system like [HiberActive](https://www.slideshare.net/martinklein0815/hiberactive)), both of which may happen arbitrarily later than when the scholarly work was authored.

### Additional Requirements

- [ ] List of entry pages to start browsing from
- [ ] Full-text search index
- [ ] Technical metadata about the web archive
- [ ] User-defined descriptive metadata
- [ ] Screenshots of key pages
- [ ] Encryption of data
- [ ] Proof of Authenticity (Signing and Verification)
- [ ] Fast access to multiple WACZ files in aggregate
- [ ] Crawl or capture logs

### How will web archives be created for this use case?

- [X] Manually, using a browser to capture exact content as directed by the user.
- [ ] Automatically, using a crawler to crawl desired content, either once or on a specified schedule.

### Sensitive private content and access

- [X] No, this use case focuses on archiving publicly accessible data only, and web archive can be made public.
- [ ] No, this use case focuses on archiving publicly data only, but web archive is not inteded to be public.
- [ ] Yes, this use case involves archiving data that is not public, and the web archive should not be made public.

**Comment by edsu** [comment]
This has been added to the current Use Cases document!
