### ISSUE TITLE
[Use Case]: website owner reconstructs local archive of lost website content from one or more web archives

### ISSUE THREAD

**Issue by nullhandle** [webrecorder/specs#90]
### Describe a use case for WACZ format.

A website owner retrieves lost website content from one or more web archives and assembles this into a local, consolidated archive (e.g., like [Warrick](https://iawebarchiving.wordpress.com/2007/02/22/warrick-a-tool-for-recovering-websites/), except saving to a more robust archival format). Ideally, this operation would leverage Memento, both for the best possible coverage but also to assemble the most temporally coherent archive.

### Additional Requirements

- [X] List of entry pages to start browsing from
- [ ] Full-text search index
- [ ] Technical metadata about the web archive
- [ ] User-defined descriptive metadata
- [ ] Screenshots of key pages
- [ ] Encryption of data
- [ ] Proof of Authenticity (Signing and Verification)
- [ ] Fast access to multiple WACZ files in aggregate
- [ ] Crawl or capture logs

### How will web archives be created for this use case?

- [ ] Manually, using a browser to capture exact content as directed by the user.
- [X] Automatically, using a crawler to crawl desired content, either once or on a specified schedule.

### Sensitive private content and access

- [X] No, this use case focuses on archiving publicly accessible data only, and web archive can be made public.
- [ ] No, this use case focuses on archiving publicly data only, but web archive is not inteded to be public.
- [ ] Yes, this use case involves archiving data that is not public, and the web archive should not be made public.

**Comment by edsu** [comment]
This has been added to the current Use Cases document.
