### ISSUE TITLE
[Use Case]: user retrieves webpages from web archives for local full-text search

### ISSUE THREAD

**Issue by nullhandle** [webrecorder/specs#92]
### Describe a use case for WACZ format.

A user wants to retrieve a bundle of webpages from a web archive (e.g., via batch downloading URLs identified and filtered using the [Wayback CDX Server API](https://github.com/internetarchive/wayback/tree/master/wayback-cdx-server)) so that full-text search can be more easily performed upon the corpus (i.e., and where full-text search isn't otherwise offered by the web archive platform).

### Additional Requirements

- [ ] List of entry pages to start browsing from
- [X] Full-text search index
- [ ] Technical metadata about the web archive
- [ ] User-defined descriptive metadata
- [ ] Screenshots of key pages
- [ ] Encryption of data
- [ ] Proof of Authenticity (Signing and Verification)
- [ ] Fast access to multiple WACZ files in aggregate
- [ ] Crawl or capture logs

### How will web archives be created for this use case?

- [ ] Manually, using a browser to capture exact content as directed by the user.
- [X] Automatically, using a crawler to crawl desired content, either once or on a specified schedule.

### Sensitive private content and access

- [X] No, this use case focuses on archiving publicly accessible data only, and web archive can be made public.
- [ ] No, this use case focuses on archiving publicly data only, but web archive is not inteded to be public.
- [ ] Yes, this use case involves archiving data that is not public, and the web archive should not be made public.

**Comment by edsu** [comment]
This has been added to the current Use Cases document.
